# Étape 1 : Utiliser Ubuntu comme image de base
FROM ubuntu:latest

# Étape 2 : Mettre à jour les paquets APT
RUN apt-get update

# Étape 3 : Mettre à niveau les logiciels installés
RUN apt-get upgrade -y

# Étape 4 : Définir la commande par défaut qui s’exécutera
CMD echo "Hello, World!"
